version: '3.3'
services:
  app:
    ports:
      - '8080:8080'
    restart: always
    image: democlinica:0.1
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root